theme: jekyll-theme-minimal
title: Sarah Schmidt's Data Projects
description: Welcome to my portfolio! Check out what I've been working on lately. <br>
Visit My <a href="http://www.linkedin.com/in/saraheschmidt">LinkedIn</a>
